import { useState, type FormEvent } from "react";

import { useAuth } from "../../auth/useAuth";
import { AdminShell } from "../AdminShell";
import { readAdminSettings, recordPasswordChange, saveAdminSettings } from "../admin-settings";

export function AdminSettingsPage() {
  const { currentUser } = useAuth();
  const fallback = { name: currentUser?.name ?? "Administrador", email: currentUser?.email ?? "", emailNotifications: true };
  const [settings, setSettings] = useState(() => readAdminSettings(fallback)); const [saved, setSaved] = useState("");
  const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [passwordMessage, setPasswordMessage] = useState("");
  function submitSettings(event: FormEvent) { event.preventDefault(); if (settings.name.trim().length < 2 || !/^\S+@\S+\.\S+$/.test(settings.email)) return setSaved("Revise o nome e o e-mail."); saveAdminSettings({ ...settings, name: settings.name.trim(), email: settings.email.trim().toLowerCase() }); setSaved("Configurações salvas neste navegador."); }
  function submitPassword(event: FormEvent) { event.preventDefault(); if (password.length < 8) return setPasswordMessage("Use pelo menos 8 caracteres."); if (password !== confirmation) return setPasswordMessage("As senhas não coincidem."); recordPasswordChange(settings.name); setPassword(""); setConfirmation(""); setPasswordMessage("Alteração simulada com sucesso."); }
  return <AdminShell title="Configurações" subtitle="Personalize a conta administrativa neste protótipo."><div className="admin-settings-grid"><section className="admin-panel"><span className="admin-section-label">Perfil</span><h2>Dados da conta</h2><form className="admin-settings-form" onSubmit={submitSettings}><label><span>Nome</span><input value={settings.name} onChange={(event) => { setSettings({ ...settings, name: event.target.value }); setSaved(""); }} /></label><label><span>E-mail</span><input type="email" value={settings.email} onChange={(event) => { setSettings({ ...settings, email: event.target.value }); setSaved(""); }} /></label><label className="admin-check"><input type="checkbox" checked={settings.emailNotifications} onChange={(event) => setSettings({ ...settings, emailNotifications: event.target.checked })} /><span>Receber notificações administrativas por e-mail</span></label>{saved ? <p className="admin-form-message" role="status">{saved}</p> : null}<button className="admin-primary-button" type="submit">Salvar configurações</button></form></section><section className="admin-panel"><span className="admin-section-label">Segurança</span><h2>Alterar senha</h2><p className="admin-settings-helper">Esta simulação não altera a senha usada no login.</p><form className="admin-settings-form" onSubmit={submitPassword}><label><span>Nova senha</span><input type="password" value={password} onChange={(event) => { setPassword(event.target.value); setPasswordMessage(""); }} /></label><label><span>Confirmar nova senha</span><input type="password" value={confirmation} onChange={(event) => { setConfirmation(event.target.value); setPasswordMessage(""); }} /></label>{passwordMessage ? <p className="admin-form-message" role="status">{passwordMessage}</p> : null}<button className="admin-primary-button" type="submit">Simular alteração</button></form></section></div></AdminShell>;
}
